swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /t_user/:
    get:
      tags:
      - t_user
      description: get TUser
      operationId: TUserController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TUser'
        "403": {}
    post:
      tags:
      - t_user
      description: create TUser
      operationId: TUserController.Post
      parameters:
      - in: body
        name: body
        description: body for TUser content
        required: true
        schema:
          $ref: '#/definitions/models.TUser'
      responses:
        "201":
          description: '{int} models.TUser'
        "403":
          description: body is empty
  /t_user/{id}:
    get:
      tags:
      - t_user
      description: get TUser by id
      operationId: TUserController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TUser'
        "403":
          description: :id is empty
    put:
      tags:
      - t_user
      description: update the TUser
      operationId: TUserController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TUser content
        required: true
        schema:
          $ref: '#/definitions/models.TUser'
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TUser'
        "403":
          description: :id is not int
    delete:
      tags:
      - t_user
      description: delete the TUser
      operationId: TUserController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /t_user2/:
    get:
      tags:
      - t_user2
      description: get TUser2
      operationId: TUser2Controller.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TUser2'
        "403": {}
    post:
      tags:
      - t_user2
      description: create TUser2
      operationId: TUser2Controller.Post
      parameters:
      - in: body
        name: body
        description: body for TUser2 content
        required: true
        schema:
          $ref: '#/definitions/models.TUser2'
      responses:
        "201":
          description: '{int} models.TUser2'
        "403":
          description: body is empty
  /t_user2/{id}:
    get:
      tags:
      - t_user2
      description: get TUser2 by id
      operationId: TUser2Controller.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TUser2'
        "403":
          description: :id is empty
    put:
      tags:
      - t_user2
      description: update the TUser2
      operationId: TUser2Controller.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TUser2 content
        required: true
        schema:
          $ref: '#/definitions/models.TUser2'
      responses:
        "200":
          schema:
            $ref: '#/definitions/models.TUser2'
        "403":
          description: :id is not int
    delete:
      tags:
      - t_user2
      description: delete the TUser2
      operationId: TUser2Controller.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  .Time:
    type: object
  models.TUser:
    title: TUser
    type: object
    properties:
      Id:
        type: integer
        format: int64
      UserName:
        type: string
      UserPaswd:
        type: string
      UserRegdata:
        $ref: '#/definitions/time.Time'
  models.TUser2:
    title: TUser2
    type: object
    properties:
      Id:
        type: integer
        format: int64
      UserName:
        type: string
      UserPaswd:
        type: string
      UserRegdata:
        $ref: '#/definitions/time.Time'
tags:
- name: t_user
  description: |
    TUserController operations for TUser
- name: t_user2
  description: |
    TUser2Controller operations for TUser2
